modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-SheepMetal/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-sheep-metal"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="sbmsheepmetal" #mandatory
version="0.2.1" #mandatory
displayName="[SBM] Sheep Metal" #mandatory
description='''Metal wool sheep''' #mandatory

[[dependencies.sbmsheepmetal]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmsheepmetal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"